### ISSUE TITLE
BUG: Choropleth intermittently misses area selection

### ISSUE THREAD

**Issue by brettvitaz** [ihmeuw/ihme-ui#25]
Steps to reproduce:

1. Click on an area to select it
1. Move the mouse and click on an area to select it

Results:
The area will intermittently not toggle selected state

Notes:
This appears to be a problem in the `onClick` code.

**Comment by GabeMedrash** [comment]
Closing this as I think it's a little stale with all the refactoring of this component since June (haven't seen this issue in the last couple months)
