### ISSUE TITLE
Button: standardize className and style props

### ISSUE THREAD

**Issue by brettvitaz** [ihmeuw/ihme-ui#76]
Icon prop should have className and style applied.

**Comment by GabeMedrash** [comment]
- Static method `calculateStyle` should be removed in favor of [combineStyles](https://github.com/ihmeuw/ihme-ui/blob/master/src/utils/style.js#L12). See https://github.com/ihmeuw/ihme-ui/commit/2d39e7e3e94ffe3f57cdacad23fda9569e2ae39c for example.
- As Brett noted above, the icon should be classable and stylable.
