### ISSUE TITLE
scatter and multi-scatter give console warnings

### ISSUE THREAD

**Issue by aaronKeel** [ihmeuw/ihme-ui#86]
`warning.js:44Warning: Failed propType: Required prop 'scales' was not specified in 'MultiScatter'. Check the render method of 'App'.`

`warning.js:44Warning: Failed propType: Required prop 'scales' was not specified in 'Scatter'. Check the render method of 'App'.`

MultiScatter and Scatter are passed scales from axis-chart. The console still logs these warnings.

**Comment by GabeMedrash** [comment]
Closed by #87
